language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bison flex

install:
  - ./install_bootstrap_compiler.sh "$HOME/mercury-bootstrap" mercury-srcdist-rotd-2018-05-23.tar.gz

env:
  - PATH="$PATH:$HOME/mercury-bootstrap"

script:
  - ./configure --prefix="$HOME/mercury-test" --enable-libgrades=hlc.gc
  - make
